### ISSUE TITLE
Are you able to reproduce CheXNet's result?

### ISSUE THREAD

**Issue by xiaoyongzhu** [taoddiao/dr.b#1]
Hi, I found your repository by searching online and looks like you are trying to reproduce Stanford ML team's result on ChestXNet. 

I am trying out the same thing and find it is a bit hard to reproduce the result (that's why I search online:)) So did you repro the result successfully?

Thanks!
Xiaoyong

**Comment by taoddiao** [comment]
@xiaoyongzhu I found it is hard to match their result as well, especially when doing 14-label classification. So I decided to train a network for each disease separately and the output seams much better.

**Comment by xiaoyongzhu** [comment]
Oh OK that's like an interesting approach. Then how does the result look like?

I also suspect doing basic data augmentation might be helpful...

Sent from my phone

-------- Original Message --------
Subject: Re: [taoddiao/dr.b] Are you able to reproduce CheXNet's result? (#1)
From: Taod
To: "taoddiao/dr.b"
CC: Xiaoyong Zhu ,Mention


@xiaoyongzhu<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxiaoyongzhu&data=04%7C01%7Cxiaoyzhu%40microsoft.com%7Cac1373bacec14aeb084c08d5444eb0a5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636490027121417671%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=3bg0qx2n9A2wAQOGPOeigEYe879c1eu3tAN%2FRbdFq0M%3D&reserved=0> I found it is hard to match their result as well, especially when doing 14-label classification. So I decided to train a network for each disease separately and the output seams much better.

**Comment by taoddiao** [comment]
The auc score ranges from 0.8 to 0.9 and the recall and precision is around 80% (threshold=0.5).
What kind of data augmentation have you done? Does it improve your results?
I am trying to use random horizontal flipping as the paper says, hope it will work.
